package.json
yarn.lock

Hi! I tried to use this in a project that uses yarn PnP, and it threw this error:
https://classic.yarnpkg.com/lang/en/docs/pnp/troubleshooting/#toc-is-trying-to-require-without-it-being-listed-in-its-dependencies
> This error simply means that the specified package is requiring something without explicitly declaring it in its dependencies. Since this behavior is unsafe and relies on the hoisting being done a certain way, Plug’n’Play doesn’t allow it.
This PR simply adds those implicit dependencies to the top level package.json. Seems like a harmless change, but happy to iterate if you have any concerns.

Add implicit dependencies to package.json

---

.github/workflows/authzed-node.yaml
package.json

Types should always be specified as devDependencies. In this particular case, the inclusion of @types/jasmine in the compiled package leads to conflicts in systems that make use of Jest

Move @types/jasmine into devDependencies

---

README.md
src/util.ts
src/v1.ts

You can now pass in a CA certificate to v1.NewClient constructor if you don't have a certificate installed on your system. For example one for localhost.

Add support for custom certs

---

src/v1.test.ts
src/v1.ts
src/v1alpha1.test.ts
src/v1alpha1.ts

The ClientSecurity enum is exported from v1.ts and v1alpha1.ts to make it publicly available at the top level.

Export ClientSecurity from v1.ts and v1alpha1.ts

---

src/v1-promise.test.ts
src/v1.test.ts
src/v1.ts

The `close` method of the grpc.Client does not correctly get proxied to each individual gRPC client that we are creating in the composite client. This PR updates the interface/proxy logic to correctly proxy the `close` method to a function that will close all known clients.

feat: support proxying close method to all clients

---

.github/workflows/authzed-node.yaml

- use only node versions under maintenance https://nodejs.org/en/about/previous-releases
- use faster buildjet runners
- do not test on lint job (seemed redundant)
- bump checkout and setup-node actions
Versions 16 and 17 are removed as they are EOL

various updates to CI pipeline

---

.github/workflows/authzed-node.yaml

recent changes to bypass CI builds when
code unrelated changes happen broke
the release process, because the release
jobs have those bypassed builds as required.
this changes the bypass condition so that
they run if the event that triggered
GitHub Actions was a release

triggers builds if github event is release

---

.github/workflows/authzed-node.yaml
src/v1-promise.test.ts
src/v1.test.ts

were removed under the
wrong assumption they were being
run elsewhere in CI

re-enable tests

---

.github/workflows/publish.yaml
.github/workflows/test.yaml

There were some things in #160 that were broken that weren't previously visible. This fixes those.
* Remove dependencies on steps that are no longer in the same file
* Do install and build steps as a part of publishing the `js-dist` version of the package
* Remove unnecessary filters in test
Review. Attempt another release.

Fix release workflow

---

.github/workflows/publish.yaml

I went and checked the npm registry and the version wasn't v1.0.1. The version getting step didn't work as desired, so the version setting step was a read-only step rather than something that set the version. This fixes that.
The version getting action is 3 years out of date at this point, so we're using a script instead of it.
* Use the script approach that works in other libs
Release and see that the version appears on npm.

Use script instead of abandoned lib

---

.github/workflows/publish.yaml

Turns out `npm version <version>` tries to commit a tag. We don't want that in this context, and it causes failures.
I also am taking a different approach to fixing the release process - this should mean that I don't need to keep cutting releases until I get the process sorted.
* Fix `npm version` invocation
* Change publish to run on PR
See that publish step completes. Then I'll revert the changes to the workflow triggers and we can merge.

Fix npm version invocation

---

.github/workflows/automatic-api-update.yaml
.github/workflows/manual-api-update.yaml
buf.gen.yaml

Part of getting all of our various libraries migrated
I ran `buf generate` as a part of this PR and there were no changes, which seems like a good sign.
* Use v2 of buf.gen.yaml
* Use new actions for API version update
Review. See that things are green.

Use remotes for code generation and update regen workflows accordingly

---

src/v1.ts

Fixes #170 
As currently written, the client decides which functions to wrap with promises based on a list of streaming endpoints in the client. When we added the new versions of `importBulk` and `exportBulk`, we didn't add them to this list, which caused the behavior seen in #170. This is a short-term fix for that. A longer-term fix would be something like #179.
* Add new methods to list of streaming methods
Review.

Add new bulk functions to list of stream endpoints

---

.github/workflows/test.yaml
README.md

Fixes #193 
Node 22 is the current LTS, and odd-numbered node versions are never LTS. We're probably okay to run only against even-numbered versions.
* Run against node 22 instead of node 21
See that tests pass with new matrix

Run tests against Node 22

---

.github/workflows/automatic-api-update.yaml
.github/workflows/cla.yaml
.github/workflows/manual-api-update.yaml

Part of making API updates an easier process. This makes the created PRs into drafts, which ensures that tests run when we move them out of draft.
* Add always draft setting
Review.

Update triggered PRs to be drafts

---

package.json

Fixes #196 
NestJS just straight-up doesn't support ESM: https://github.com/nestjs/nest/pull/8736
We've got some users who are using Nest and this is a stumbling point for them. Adding a CJS export isn't super costly for us (other than increasing the size of the bundle by a bit). We can revisit dropping this at some point in the future if desired.
* Add `postbuild` that uses rollup to generate a CJS output
* Add package.json fields that reference the CJS output
Review. Release this as a point release and notify users. See if it works with nest.

Re-add support for cjs

---

js-dist/package.json
package.json

Part of #206 
Users reported breakage of the `authzed-node` lib related to our `KnownInsecureChannelCredentials` implementation (see issue for details). This appears to be related to the v1.13.0 or v1.13.1 release of grpc-js, though it's unclear what part of those releases would be related.
* Pin grpc-js temporarily to v1.12.x (using `~` instead of `^`)
Review. See that tests pass.

Pin grpc-js temporarily to work around issue

---

package.json

Fixes #219 
Credit to @noseworthy for the fix
Before
With this fix
Notice how the import and types are found correctly.

CJS fix - fixes #219

---

package.json
src/v1-promise.test.ts

A user asked in #224 how to put caveat context in relationships; this test should demonstrate how it's done, and the test passing indicates that it's working.
* Add a separate test for caveats where the context is set on the relation rather than on the request
* Remove some overspecified options
* Add an alias for formatting
Review. See that tests pass.

Add test with caveat context in relation

---

README.md

Adding some documentation per what we observed in #224. This should help folks find this problem before they run into it.
* Add some new content to README
Review

Update caveat context writing documentation

---

README.md
examples/v1/example.js

https://github.com/authzed/authzed-node/issues/43

update code snippets

---

src/v1.ts

This was raised by a discord user: https://discord.com/channels/844600078504951838/844600078948630559/1424792180207128588
Everything in this library that needs to be exposed needs to be explicitly exported. The `ErrorReason` enum wasn't one of those things. This fixes that.
* Export the `ErrorReason` enum
Review. See that tests pass. See that you can then import the `ErrorReason` enum and compare against it.

Expose ErrorReason enum in exports
